# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMTK_server', '0006_datafile_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsamplefile',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
