# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 02:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMTK_server', '0008_default_toolsample_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='field_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='units',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='toolconfig',
            name='json_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='toolsampleconfig',
            name='sample_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
